import { User, Project, Task, ProductivityMetric, DailyProductivity, ActivityItem } from '@/types';

export const CURRENT_USER: User = {
  id: 'usr-1',
  name: 'Alex Morgan',
  email: 'alex.morgan@devcorp.io',
  role: 'Senior Full Stack Engineer',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  initials: 'AM',
  status: 'flow',
  statusMessage: 'Deep work on Auth Gateway optimization',
  weeklyFocusGoalHours: 35,
};

export const TEAM_MEMBERS: User[] = [
  CURRENT_USER,
  {
    id: 'usr-2',
    name: 'Elena Rostova',
    email: 'elena.r@devcorp.io',
    role: 'Tech Lead / Architect',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    initials: 'ER',
    status: 'in_review',
    statusMessage: 'Reviewing sprint PRs',
    weeklyFocusGoalHours: 30,
  },
  {
    id: 'usr-3',
    name: 'Marcus Chen',
    email: 'marcus.c@devcorp.io',
    role: 'Frontend Engineer',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    initials: 'MC',
    status: 'available',
    statusMessage: 'Refactoring design system tokens',
    weeklyFocusGoalHours: 32,
  },
  {
    id: 'usr-4',
    name: 'Sarah Jenkins',
    email: 'sarah.j@devcorp.io',
    role: 'DevOps Specialist',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    initials: 'SJ',
    status: 'flow',
    statusMessage: 'Kubernetes autoscaling rollout',
    weeklyFocusGoalHours: 35,
  },
  {
    id: 'usr-5',
    name: 'David Kim',
    email: 'david.k@devcorp.io',
    role: 'Backend Engineer',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    initials: 'DK',
    status: 'away',
    statusMessage: 'In team planning meeting',
    weeklyFocusGoalHours: 28,
  },
];

export const PRODUCTIVITY_METRICS: ProductivityMetric[] = [
  {
    id: 'met-1',
    label: 'Focus Score',
    value: '91%',
    changePercent: 6.4,
    trend: 'up',
    description: 'Deep uninterrupted focus time vs total logged',
    iconName: 'Zap',
  },
  {
    id: 'met-2',
    label: 'Sprint Velocity',
    value: '38 pts',
    unit: '/ 42 pts',
    changePercent: 12.5,
    trend: 'up',
    description: 'Story points delivered in current sprint cycle',
    iconName: 'Flame',
  },
  {
    id: 'met-3',
    label: 'Active Code Reviews',
    value: '4 PRs',
    unit: '2 pending',
    changePercent: -15.0,
    trend: 'down',
    description: 'Average turnaround review time: 1.8 hrs',
    iconName: 'GitPullRequest',
  },
  {
    id: 'met-4',
    label: 'Focus Hours Logged',
    value: '31.5h',
    unit: '/ 35h goal',
    changePercent: 4.8,
    trend: 'up',
    description: '90% of weekly deep work target reached',
    iconName: 'Clock',
  },
];

export const WEEKLY_PRODUCTIVITY_DATA: DailyProductivity[] = [
  { day: 'Monday', shortDay: 'Mon', focusHours: 6.8, commitCount: 9, pullRequestsCount: 2, tasksCompleted: 4 },
  { day: 'Tuesday', shortDay: 'Tue', focusHours: 7.4, commitCount: 14, pullRequestsCount: 4, tasksCompleted: 6 },
  { day: 'Wednesday', shortDay: 'Wed', focusHours: 5.9, commitCount: 8, pullRequestsCount: 3, tasksCompleted: 3 },
  { day: 'Thursday', shortDay: 'Thu', focusHours: 7.8, commitCount: 16, pullRequestsCount: 5, tasksCompleted: 7, isToday: true },
  { day: 'Friday', shortDay: 'Fri', focusHours: 3.6, commitCount: 4, pullRequestsCount: 1, tasksCompleted: 2 },
  { day: 'Saturday', shortDay: 'Sat', focusHours: 0, commitCount: 0, pullRequestsCount: 0, tasksCompleted: 0 },
  { day: 'Sunday', shortDay: 'Sun', focusHours: 0, commitCount: 0, pullRequestsCount: 0, tasksCompleted: 0 },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Unified Developer Platform',
    key: 'UDP',
    description: 'Centralized observability, CI/CD telemetry, and internal microservice developer portal.',
    status: 'on_track',
    progress: 74,
    totalTasks: 28,
    completedTasks: 21,
    deadline: '2026-09-15',
    repository: 'github.com/devcorp/unified-platform',
    techStack: ['Next.js', 'TypeScript', 'Tailwind', 'GraphQL'],
    lead: CURRENT_USER,
    members: [CURRENT_USER, TEAM_MEMBERS[1], TEAM_MEMBERS[2]],
    color: 'from-blue-600 to-indigo-600',
  },
  {
    id: 'proj-2',
    name: 'Auth Gateway v2 & Session Zero',
    key: 'AGW',
    description: 'High throughput OAuth2/PKCE token exchange and edge latency caching layer.',
    status: 'on_track',
    progress: 88,
    totalTasks: 16,
    completedTasks: 14,
    deadline: '2026-09-02',
    repository: 'github.com/devcorp/auth-gateway-v2',
    techStack: ['Rust', 'Redis', 'Docker', 'JWT'],
    lead: TEAM_MEMBERS[1],
    members: [CURRENT_USER, TEAM_MEMBERS[1], TEAM_MEMBERS[4]],
    color: 'from-emerald-600 to-teal-600',
  },
  {
    id: 'proj-3',
    name: 'Design System & Component Kit',
    key: 'DSK',
    description: 'Standardized accessible component library with tokens, dark mode and automated visual regression.',
    status: 'at_risk',
    progress: 45,
    totalTasks: 34,
    completedTasks: 15,
    deadline: '2026-09-28',
    repository: 'github.com/devcorp/design-system',
    techStack: ['React', 'Tailwind CSS', 'Storybook', 'Figma'],
    lead: TEAM_MEMBERS[2],
    members: [TEAM_MEMBERS[2], CURRENT_USER],
    color: 'from-purple-600 to-pink-600',
  },
  {
    id: 'proj-4',
    name: 'K8s Cluster Auto-Scaler',
    key: 'K8S',
    description: 'Automated node pool scaling based on real-time traffic spikes and cost budget limits.',
    status: 'on_track',
    progress: 60,
    totalTasks: 20,
    completedTasks: 12,
    deadline: '2026-10-05',
    repository: 'github.com/devcorp/infra-autoscaler',
    techStack: ['Go', 'Kubernetes', 'Terraform', 'Prometheus'],
    lead: TEAM_MEMBERS[3],
    members: [TEAM_MEMBERS[3], TEAM_MEMBERS[4]],
    color: 'from-amber-600 to-orange-600',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-101',
    title: 'Implement JWT refresh rotation & revoked token blacklist',
    description: 'Add Redis blacklist checks for token invalidation during logout and password resets.',
    projectId: 'proj-2',
    projectName: 'Auth Gateway v2 & Session Zero',
    priority: 'urgent',
    status: 'in_progress',
    assignee: CURRENT_USER,
    dueDate: '2026-08-30',
    estimatedHours: 6,
    loggedHours: 4.5,
    subtasks: [
      { id: 'sub-1', title: 'Write Redis expiration key schema', completed: true },
      { id: 'sub-2', title: 'Implement middleware revocation check', completed: true },
      { id: 'sub-3', title: 'Add unit tests for expired session cases', completed: false },
    ],
    tags: ['Security', 'Redis', 'Auth'],
    branchName: 'feat/redis-jwt-blacklist',
    prNumber: 342,
    createdAt: '2026-08-22',
  },
  {
    id: 'task-102',
    title: 'Build search and filter controls for Project Hub',
    description: 'Support multi-parameter filtering across project health, tech stacks, and team members.',
    projectId: 'proj-1',
    projectName: 'Unified Developer Platform',
    priority: 'high',
    status: 'in_progress',
    assignee: CURRENT_USER,
    dueDate: '2026-09-01',
    estimatedHours: 4,
    loggedHours: 2.5,
    subtasks: [
      { id: 'sub-4', title: 'Create reusable search input with debounce', completed: true },
      { id: 'sub-5', title: 'Build status and tag filter pills', completed: false },
      { id: 'sub-6', title: 'Handle empty filter state gracefully', completed: false },
    ],
    tags: ['Frontend', 'UI/UX', 'Search'],
    branchName: 'feat/project-filters',
    prNumber: 345,
    createdAt: '2026-08-24',
  },
  {
    id: 'task-103',
    title: 'Migrate legacy CSS classes to Tailwind CSS v4 design tokens',
    description: 'Replace hardcoded color hexes and spacing with semantic variables across all modals.',
    projectId: 'proj-3',
    projectName: 'Design System & Component Kit',
    priority: 'medium',
    status: 'in_review',
    assignee: TEAM_MEMBERS[2],
    dueDate: '2026-09-04',
    estimatedHours: 8,
    loggedHours: 7.5,
    subtasks: [
      { id: 'sub-7', title: 'Audit all modal and popup components', completed: true },
      { id: 'sub-8', title: 'Replace hex values with CSS theme tokens', completed: true },
      { id: 'sub-9', title: 'Verify dark mode contrast ratios', completed: true },
    ],
    tags: ['Tailwind', 'Refactor', 'Tokens'],
    branchName: 'refactor/tailwind-tokens',
    prNumber: 118,
    createdAt: '2026-08-20',
  },
  {
    id: 'task-104',
    title: 'Configure Prometheus metrics endpoint for cluster autoscaler',
    description: 'Expose Prometheus gauge metrics for pending pod queue depth and scale-up latency.',
    projectId: 'proj-4',
    projectName: 'K8s Cluster Auto-Scaler',
    priority: 'medium',
    status: 'completed',
    assignee: TEAM_MEMBERS[3],
    dueDate: '2026-08-26',
    estimatedHours: 5,
    loggedHours: 4.8,
    subtasks: [
      { id: 'sub-10', title: 'Define custom Prometheus collector', completed: true },
      { id: 'sub-11', title: 'Deploy test scrape config in staging', completed: true },
      { id: 'sub-12', title: 'Setup Grafana dashboard alerts', completed: true },
    ],
    tags: ['DevOps', 'Prometheus', 'Monitoring'],
    branchName: 'feat/k8s-prometheus-metrics',
    prNumber: 89,
    createdAt: '2026-08-18',
  },
  {
    id: 'task-105',
    title: 'Benchmark GraphQL query latency on developer activity feed',
    description: 'Identify slow resolver bottlenecks and apply DataLoader batch caching for user avatars.',
    projectId: 'proj-1',
    projectName: 'Unified Developer Platform',
    priority: 'high',
    status: 'backlog',
    assignee: TEAM_MEMBERS[4],
    dueDate: '2026-09-10',
    estimatedHours: 6,
    loggedHours: 0,
    subtasks: [
      { id: 'sub-13', title: 'Run k6 load test script against staging', completed: false },
      { id: 'sub-14', title: 'Implement DataLoader pattern on author field', completed: false },
      { id: 'sub-15', title: 'Profile database query execution plans', completed: false },
    ],
    tags: ['Performance', 'GraphQL', 'Backend'],
    createdAt: '2026-08-25',
  },
  {
    id: 'task-106',
    title: 'Setup automated Playwright E2E testing pipeline in CI',
    description: 'Ensure smoke test suite runs against preview environments before any merge to main.',
    projectId: 'proj-1',
    projectName: 'Unified Developer Platform',
    priority: 'low',
    status: 'backlog',
    assignee: TEAM_MEMBERS[1],
    dueDate: '2026-09-18',
    estimatedHours: 4,
    loggedHours: 0,
    subtasks: [
      { id: 'sub-16', title: 'Create GitHub Actions workflow matrix', completed: false },
      { id: 'sub-17', title: 'Write critical user authentication flow spec', completed: false },
    ],
    tags: ['Testing', 'CI/CD', 'Playwright'],
    createdAt: '2026-08-26',
  },
];

export const RECENT_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'commit',
    title: 'Pushed 3 commits to feat/redis-jwt-blacklist',
    description: 'Added fast Redis pipeline revocation lookup and TTL sync test cases.',
    timestamp: '2026-08-26T23:45:00Z',
    user: CURRENT_USER,
    projectKey: 'AGW',
    badgeText: '3 commits',
  },
  {
    id: 'act-2',
    type: 'pr_review',
    title: 'Reviewed and approved PR #118',
    description: 'Tailwind CSS v4 design token migration looks crisp and passes visual contrast checks.',
    timestamp: '2026-08-26T22:15:00Z',
    user: TEAM_MEMBERS[1],
    projectKey: 'DSK',
    badgeText: 'Approved',
  },
  {
    id: 'act-3',
    type: 'deployment',
    title: 'Deployed staging build v2.4.1',
    description: 'Autoscaler pod monitor successfully provisioned in us-east-1 cluster.',
    timestamp: '2026-08-26T20:30:00Z',
    user: TEAM_MEMBERS[3],
    projectKey: 'K8S',
    badgeText: 'Staging OK',
  },
  {
    id: 'act-4',
    type: 'task_completed',
    title: 'Completed task #104: Prometheus metrics endpoint',
    description: 'All 3 subtasks verified with passing health probes.',
    timestamp: '2026-08-26T18:10:00Z',
    user: TEAM_MEMBERS[3],
    projectKey: 'K8S',
    badgeText: 'Done',
  },
  {
    id: 'act-5',
    type: 'pr_merged',
    title: 'Merged PR #338 into main',
    description: 'Fixed CORS header inconsistency across subdomains.',
    timestamp: '2026-08-26T15:00:00Z',
    user: TEAM_MEMBERS[4],
    projectKey: 'AGW',
    badgeText: 'Merged',
  },
];
