import { User, Project, Task, ProductivityMetric, DailyProductivity, ActivityItem } from '@/types';

export const CURRENT_USER: User = {
  id: 'usr-1',
  name: 'Pankaj Prajapati',
  email: 'pankaj.prajapati@devhub.io',
  role: 'AI & Full Stack Developer',
  avatarUrl: '/pankaj.jpg',
  initials: 'PP',
  status: 'flow',
  statusMessage: 'Deep work on Developer Productivity Dashboard & AI integrations',
  weeklyFocusGoalHours: 35,
};

export const TEAM_MEMBERS: User[] = [
  CURRENT_USER,
  {
    id: 'usr-2',
    name: 'Elena Rostova',
    email: 'elena.r@devhub.io',
    role: 'Tech Lead / Architect',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    initials: 'ER',
    status: 'in_review',
    statusMessage: 'Reviewing sprint PRs',
    weeklyFocusGoalHours: 30,
  },
  {
    id: 'usr-3',
    name: 'Marcus Chen',
    email: 'marcus.c@devhub.io',
    role: 'Frontend Engineer',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    initials: 'MC',
    status: 'available',
    statusMessage: 'Refactoring design system tokens',
    weeklyFocusGoalHours: 32,
  },
  {
    id: 'usr-4',
    name: 'Sarah Jenkins',
    email: 'sarah.j@devhub.io',
    role: 'DevOps Specialist',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    initials: 'SJ',
    status: 'flow',
    statusMessage: 'Kubernetes autoscaling rollout',
    weeklyFocusGoalHours: 35,
  },
  {
    id: 'usr-5',
    name: 'David Kim',
    email: 'david.k@devhub.io',
    role: 'Backend Engineer',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    initials: 'DK',
    status: 'away',
    statusMessage: 'In team planning meeting',
    weeklyFocusGoalHours: 28,
  },
];

export const PRODUCTIVITY_METRICS: ProductivityMetric[] = [
  {
    id: 'met-1',
    label: 'Focus Score',
    value: '91%',
    changePercent: 6.4,
    trend: 'up',
    description: 'Deep uninterrupted focus time vs total logged',
    iconName: 'Zap',
  },
  {
    id: 'met-2',
    label: 'Sprint Velocity',
    value: '38 pts',
    unit: '/ 42 pts',
    changePercent: 12.5,
    trend: 'up',
    description: 'Story points delivered in current sprint cycle',
    iconName: 'Flame',
  },
  {
    id: 'met-3',
    label: 'Active Code Reviews',
    value: '4 PRs',
    unit: '2 pending',
    changePercent: -15.0,
    trend: 'down',
    description: 'Average turnaround review time: 1.8 hrs',
    iconName: 'GitPullRequest',
  },
  {
    id: 'met-4',
    label: 'Focus Hours Logged',
    value: '31.5h',
    unit: '/ 35h goal',
    changePercent: 4.8,
    trend: 'up',
    description: '90% of weekly deep work target reached',
    iconName: 'Clock',
  },
];

export const WEEKLY_PRODUCTIVITY_DATA: DailyProductivity[] = [
  { day: 'Monday', shortDay: 'Mon', focusHours: 6.8, commitCount: 9, pullRequestsCount: 2, tasksCompleted: 4 },
  { day: 'Tuesday', shortDay: 'Tue', focusHours: 7.4, commitCount: 14, pullRequestsCount: 4, tasksCompleted: 6 },
  { day: 'Wednesday', shortDay: 'Wed', focusHours: 5.9, commitCount: 8, pullRequestsCount: 3, tasksCompleted: 3 },
  { day: 'Thursday', shortDay: 'Thu', focusHours: 7.8, commitCount: 16, pullRequestsCount: 5, tasksCompleted: 7, isToday: true },
  { day: 'Friday', shortDay: 'Fri', focusHours: 3.6, commitCount: 4, pullRequestsCount: 1, tasksCompleted: 2 },
  { day: 'Saturday', shortDay: 'Sat', focusHours: 0, commitCount: 0, pullRequestsCount: 0, tasksCompleted: 0 },
  { day: 'Sunday', shortDay: 'Sun', focusHours: 0, commitCount: 0, pullRequestsCount: 0, tasksCompleted: 0 },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-dpd',
    name: 'Developer Productivity Dashboard Platform',
    key: 'DPD',
    description: 'Modern developer productivity hub tracking weekly focus hours, sprint velocity, task boards, and telemetry.',
    status: 'on_track',
    progress: 90,
    totalTasks: 20,
    completedTasks: 18,
    deadline: '2026-09-05',
    repository: 'github.com/prajapati-pankaj-31/developer-productivity-dashboard',
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Lucide React'],
    lead: CURRENT_USER,
    members: [CURRENT_USER, TEAM_MEMBERS[1], TEAM_MEMBERS[2]],
    color: 'from-indigo-600 to-blue-600',
  },
  {
    id: 'proj-saq',
    name: 'Smart Appointment / Queue Management System',
    key: 'SAQ',
    description: 'Automated appointment booking, doctor/service slot allocation, and real-time digital queue management platform.',
    status: 'on_track',
    progress: 82,
    totalTasks: 22,
    completedTasks: 18,
    deadline: '2026-09-20',
    repository: 'github.com/prajapati-pankaj-31/smart-appointment-queue',
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Node.js'],
    lead: CURRENT_USER,
    members: [CURRENT_USER, TEAM_MEMBERS[1], TEAM_MEMBERS[3]],
    color: 'from-blue-600 to-indigo-600',
  },
  {
    id: 'proj-qfs',
    name: 'QR-Based File Sharing System',
    key: 'QFS',
    description: 'Instant QR-driven secure file sharing system with fast upload/download link generation and chunked file transfer.',
    status: 'on_track',
    progress: 75,
    totalTasks: 16,
    completedTasks: 12,
    deadline: '2026-09-10',
    repository: 'github.com/prajapati-pankaj-31/qr-file-sharing',
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'WebSockets'],
    lead: CURRENT_USER,
    members: [CURRENT_USER, TEAM_MEMBERS[2]],
    color: 'from-purple-600 to-pink-600',
  },
  {
    id: 'proj-tfd',
    name: 'Tomoto – Food Delivery System',
    key: 'TFD',
    description: 'End-to-end food ordering and delivery system with live menu browsing, cart management, and real-time order tracking.',
    status: 'on_track',
    progress: 68,
    totalTasks: 25,
    completedTasks: 17,
    deadline: '2026-09-30',
    repository: 'github.com/prajapati-pankaj-31/tomoto-food-delivery',
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'REST API'],
    lead: CURRENT_USER,
    members: [CURRENT_USER, TEAM_MEMBERS[3], TEAM_MEMBERS[4]],
    color: 'from-amber-600 to-orange-600',
  },
  {
    id: 'proj-1',
    name: 'Unified Developer Platform',
    key: 'UDP',
    description: 'Centralized observability, CI/CD telemetry, and internal microservice developer portal.',
    status: 'on_track',
    progress: 74,
    totalTasks: 28,
    completedTasks: 21,
    deadline: '2026-09-15',
    repository: 'github.com/devcorp/unified-platform',
    techStack: ['Next.js', 'TypeScript', 'Tailwind', 'GraphQL'],
    lead: CURRENT_USER,
    members: [CURRENT_USER, TEAM_MEMBERS[1], TEAM_MEMBERS[2]],
    color: 'from-blue-600 to-indigo-600',
  },
  {
    id: 'proj-2',
    name: 'Auth Gateway v2 & Session Zero',
    key: 'AGW',
    description: 'High throughput OAuth2/PKCE token exchange and edge latency caching layer.',
    status: 'on_track',
    progress: 88,
    totalTasks: 16,
    completedTasks: 14,
    deadline: '2026-09-02',
    repository: 'github.com/devcorp/auth-gateway-v2',
    techStack: ['Rust', 'Redis', 'Docker', 'JWT'],
    lead: TEAM_MEMBERS[1],
    members: [CURRENT_USER, TEAM_MEMBERS[1], TEAM_MEMBERS[4]],
    color: 'from-emerald-600 to-teal-600',
  },
  {
    id: 'proj-3',
    name: 'Design System & Component Kit',
    key: 'DSK',
    description: 'Standardized accessible component library with tokens, dark mode and automated visual regression.',
    status: 'at_risk',
    progress: 45,
    totalTasks: 34,
    completedTasks: 15,
    deadline: '2026-09-28',
    repository: 'github.com/devcorp/design-system',
    techStack: ['React', 'Tailwind CSS', 'Storybook', 'Figma'],
    lead: TEAM_MEMBERS[2],
    members: [TEAM_MEMBERS[2], CURRENT_USER],
    color: 'from-purple-600 to-pink-600',
  },
  {
    id: 'proj-4',
    name: 'K8s Cluster Auto-Scaler',
    key: 'K8S',
    description: 'Automated node pool scaling based on real-time traffic spikes and cost budget limits.',
    status: 'on_track',
    progress: 60,
    totalTasks: 20,
    completedTasks: 12,
    deadline: '2026-10-05',
    repository: 'github.com/devcorp/infra-autoscaler',
    techStack: ['Go', 'Kubernetes', 'Terraform', 'Prometheus'],
    lead: TEAM_MEMBERS[3],
    members: [TEAM_MEMBERS[3], TEAM_MEMBERS[4]],
    color: 'from-amber-600 to-orange-600',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-201',
    title: 'Fix appointment booking validation and time-slot conflicts',
    description: 'Prevent overlapping slot bookings and handle dynamic buffer time between consultations.',
    projectId: 'proj-saq',
    projectName: 'Smart Appointment / Queue Management System',
    priority: 'urgent',
    status: 'in_progress',
    assignee: CURRENT_USER,
    dueDate: '2026-09-02',
    estimatedHours: 5,
    loggedHours: 3.5,
    subtasks: [
      { id: 'sub-saq-1', title: 'Add overlap validation query logic', completed: true },
      { id: 'sub-saq-2', title: 'Handle timezone offset normalization', completed: true },
      { id: 'sub-saq-3', title: 'Write unit tests for edge slot boundary cases', completed: false },
    ],
    tags: ['Appointments', 'Validation', 'Booking'],
    branchName: 'fix/slot-overlap-validation',
    prNumber: 48,
    createdAt: '2026-08-25',
  },
  {
    id: 'task-202',
    title: 'Improve queue management flow and live queue ticket tracker',
    description: 'Implement real-time queue position counter and estimated waiting time calculations.',
    projectId: 'proj-saq',
    projectName: 'Smart Appointment / Queue Management System',
    priority: 'high',
    status: 'in_review',
    assignee: CURRENT_USER,
    dueDate: '2026-09-06',
    estimatedHours: 6,
    loggedHours: 5.5,
    subtasks: [
      { id: 'sub-saq-4', title: 'Design live ticket tracker component', completed: true },
      { id: 'sub-saq-5', title: 'Sync queue state with polling updates', completed: true },
      { id: 'sub-saq-6', title: 'Add SMS/notification alert triggers', completed: true },
    ],
    tags: ['Queue', 'Realtime', 'UI/UX'],
    branchName: 'feat/queue-ticket-tracker',
    prNumber: 52,
    createdAt: '2026-08-26',
  },
  {
    id: 'task-203',
    title: 'Build QR-based file sharing workflow and QR code generator',
    description: 'Generate dynamic QR codes for rapid mobile-to-desktop file handoff with expiration TTL.',
    projectId: 'proj-qfs',
    projectName: 'QR-Based File Sharing System',
    priority: 'high',
    status: 'in_progress',
    assignee: CURRENT_USER,
    dueDate: '2026-09-04',
    estimatedHours: 4,
    loggedHours: 3.0,
    subtasks: [
      { id: 'sub-qfs-1', title: 'Integrate dynamic SVG QR renderer', completed: true },
      { id: 'sub-qfs-2', title: 'Implement temporary download token generator', completed: true },
      { id: 'sub-qfs-3', title: 'Add one-click copy shareable link', completed: false },
    ],
    tags: ['QR-Code', 'FileSharing', 'Security'],
    branchName: 'feat/qr-file-workflow',
    prNumber: 42,
    createdAt: '2026-08-24',
  },
  {
    id: 'task-204',
    title: 'Implement chunked file upload and download integrity verification',
    description: 'Support seamless resume for large file transfers with SHA-256 checksum verification.',
    projectId: 'proj-qfs',
    projectName: 'QR-Based File Sharing System',
    priority: 'medium',
    status: 'backlog',
    assignee: TEAM_MEMBERS[2],
    dueDate: '2026-09-08',
    estimatedHours: 6,
    loggedHours: 0,
    subtasks: [
      { id: 'sub-qfs-4', title: 'Write multipart chunk upload handler', completed: false },
      { id: 'sub-qfs-5', title: 'Add client-side checksum validator', completed: false },
    ],
    tags: ['Upload', 'Chunking', 'Performance'],
    createdAt: '2026-08-28',
  },
  {
    id: 'task-205',
    title: 'Improve food browsing, restaurant filtering, and ordering flow',
    description: 'Optimize menu grid search, category filters, and dietary preference toggle badges.',
    projectId: 'proj-tfd',
    projectName: 'Tomoto – Food Delivery System',
    priority: 'high',
    status: 'in_progress',
    assignee: CURRENT_USER,
    dueDate: '2026-09-07',
    estimatedHours: 5,
    loggedHours: 3.8,
    subtasks: [
      { id: 'sub-tfd-1', title: 'Build dietary tag filter pills (Veg, Vegan, Non-Veg)', completed: true },
      { id: 'sub-tfd-2', title: 'Optimize menu search with instant debounce', completed: true },
      { id: 'sub-tfd-3', title: 'Refine cart total and delivery charge breakdown', completed: false },
    ],
    tags: ['FoodDelivery', 'Frontend', 'Ordering'],
    branchName: 'feat/menu-browsing-filters',
    prNumber: 29,
    createdAt: '2026-08-26',
  },
  {
    id: 'task-206',
    title: 'Implement order management and real-time delivery tracking',
    description: 'Build delivery partner status cards, live step indicator, and order history archive.',
    projectId: 'proj-tfd',
    projectName: 'Tomoto – Food Delivery System',
    priority: 'medium',
    status: 'in_review',
    assignee: TEAM_MEMBERS[3],
    dueDate: '2026-09-12',
    estimatedHours: 7,
    loggedHours: 6.5,
    subtasks: [
      { id: 'sub-tfd-4', title: 'Create order status stepper (Placed, Preparing, On Route, Delivered)', completed: true },
      { id: 'sub-tfd-5', title: 'Build driver contact and estimated ETA card', completed: true },
      { id: 'sub-tfd-6', title: 'Add invoice download PDF generator', completed: true },
    ],
    tags: ['OrderTracking', 'Delivery', 'UI'],
    branchName: 'feat/order-status-stepper',
    prNumber: 31,
    createdAt: '2026-08-22',
  },
  {
    id: 'task-207',
    title: 'Build responsive developer dashboard UI with productivity metrics',
    description: 'Construct clean dashboard layout with focus timer, weekly velocity bar charts, and task board.',
    projectId: 'proj-dpd',
    projectName: 'Developer Productivity Dashboard',
    priority: 'urgent',
    status: 'completed',
    assignee: CURRENT_USER,
    dueDate: '2026-08-28',
    estimatedHours: 8,
    loggedHours: 8.0,
    subtasks: [
      { id: 'sub-dpd-1', title: 'Build responsive sidebar and top header', completed: true },
      { id: 'sub-dpd-2', title: 'Create interactive focus timer widget', completed: true },
      { id: 'sub-dpd-3', title: 'Implement multi-parameter task filters and modal dialogs', completed: true },
    ],
    tags: ['Next.js', 'TailwindCSS', 'Dashboard'],
    branchName: 'feat/dashboard-ui',
    prNumber: 1,
    createdAt: '2026-08-24',
  },
  {
    id: 'task-208',
    title: 'Prepare GitHub documentation and project walkthrough',
    description: 'Draft comprehensive README, architectural guidelines, local setup steps, and verification logs.',
    projectId: 'proj-dpd',
    projectName: 'Developer Productivity Dashboard',
    priority: 'low',
    status: 'completed',
    assignee: CURRENT_USER,
    dueDate: '2026-08-29',
    estimatedHours: 3,
    loggedHours: 2.5,
    subtasks: [
      { id: 'sub-dpd-4', title: 'Document feature breakdown and tech stack', completed: true },
      { id: 'sub-dpd-5', title: 'Add structure diagrams and run scripts', completed: true },
    ],
    tags: ['Docs', 'GitHub', 'Markdown'],
    createdAt: '2026-08-27',
  },
  {
    id: 'task-101',
    title: 'Implement JWT refresh rotation & revoked token blacklist',
    description: 'Add Redis blacklist checks for token invalidation during logout and password resets.',
    projectId: 'proj-2',
    projectName: 'Auth Gateway v2 & Session Zero',
    priority: 'urgent',
    status: 'in_progress',
    assignee: CURRENT_USER,
    dueDate: '2026-08-30',
    estimatedHours: 6,
    loggedHours: 4.5,
    subtasks: [
      { id: 'sub-1', title: 'Write Redis expiration key schema', completed: true },
      { id: 'sub-2', title: 'Implement middleware revocation check', completed: true },
      { id: 'sub-3', title: 'Add unit tests for expired session cases', completed: false },
    ],
    tags: ['Security', 'Redis', 'Auth'],
    branchName: 'feat/redis-jwt-blacklist',
    prNumber: 342,
    createdAt: '2026-08-22',
  },
  {
    id: 'task-103',
    title: 'Migrate legacy CSS classes to Tailwind CSS v4 design tokens',
    description: 'Replace hardcoded color hexes and spacing with semantic variables across all modals.',
    projectId: 'proj-3',
    projectName: 'Design System & Component Kit',
    priority: 'medium',
    status: 'in_review',
    assignee: TEAM_MEMBERS[2],
    dueDate: '2026-09-04',
    estimatedHours: 8,
    loggedHours: 7.5,
    subtasks: [
      { id: 'sub-7', title: 'Audit all modal and popup components', completed: true },
      { id: 'sub-8', title: 'Replace hex values with CSS theme tokens', completed: true },
      { id: 'sub-9', title: 'Verify dark mode contrast ratios', completed: true },
    ],
    tags: ['Tailwind', 'Refactor', 'Tokens'],
    branchName: 'refactor/tailwind-tokens',
    prNumber: 118,
    createdAt: '2026-08-20',
  },
  {
    id: 'task-104',
    title: 'Configure Prometheus metrics endpoint for cluster autoscaler',
    description: 'Expose Prometheus gauge metrics for pending pod queue depth and scale-up latency.',
    projectId: 'proj-4',
    projectName: 'K8s Cluster Auto-Scaler',
    priority: 'medium',
    status: 'completed',
    assignee: TEAM_MEMBERS[3],
    dueDate: '2026-08-26',
    estimatedHours: 5,
    loggedHours: 4.8,
    subtasks: [
      { id: 'sub-10', title: 'Define custom Prometheus collector', completed: true },
      { id: 'sub-11', title: 'Deploy test scrape config in staging', completed: true },
      { id: 'sub-12', title: 'Setup Grafana dashboard alerts', completed: true },
    ],
    tags: ['DevOps', 'Prometheus', 'Monitoring'],
    branchName: 'feat/k8s-prometheus-metrics',
    prNumber: 89,
    createdAt: '2026-08-18',
  },
  {
    id: 'task-105',
    title: 'Benchmark GraphQL query latency on developer activity feed',
    description: 'Identify slow resolver bottlenecks and apply DataLoader batch caching for user avatars.',
    projectId: 'proj-1',
    projectName: 'Unified Developer Platform',
    priority: 'high',
    status: 'backlog',
    assignee: TEAM_MEMBERS[4],
    dueDate: '2026-09-10',
    estimatedHours: 6,
    loggedHours: 0,
    subtasks: [
      { id: 'sub-13', title: 'Run k6 load test script against staging', completed: false },
      { id: 'sub-14', title: 'Implement DataLoader pattern on author field', completed: false },
      { id: 'sub-15', title: 'Profile database query execution plans', completed: false },
    ],
    tags: ['Performance', 'GraphQL', 'Backend'],
    createdAt: '2026-08-25',
  },
];

export const RECENT_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'commit',
    title: 'Pushed 3 commits to fix/slot-overlap-validation',
    description: 'Added slot collision verification and dynamic consultation buffer handling.',
    timestamp: '2026-08-29T14:30:00Z',
    user: CURRENT_USER,
    projectKey: 'SAQ',
    badgeText: '3 commits',
  },
  {
    id: 'act-2',
    type: 'task_completed',
    title: 'Completed task #207: Responsive developer dashboard UI',
    description: 'Verified focus timer, weekly productivity chart, and task filtering.',
    timestamp: '2026-08-29T11:15:00Z',
    user: CURRENT_USER,
    projectKey: 'DPD',
    badgeText: 'Completed',
  },
  {
    id: 'act-3',
    type: 'pr_merged',
    title: 'Merged PR #42: Dynamic QR code generator workflow',
    description: 'Validated SVG QR rendering and instant mobile file handoff tokens.',
    timestamp: '2026-08-28T22:00:00Z',
    user: CURRENT_USER,
    projectKey: 'QFS',
    badgeText: 'Merged',
  },
  {
    id: 'act-4',
    type: 'pr_review',
    title: 'Reviewed and approved PR #118',
    description: 'Tailwind CSS v4 design token migration looks crisp and passes visual contrast checks.',
    timestamp: '2026-08-28T18:15:00Z',
    user: TEAM_MEMBERS[1],
    projectKey: 'DSK',
    badgeText: 'Approved',
  },
  {
    id: 'act-5',
    type: 'commit',
    title: 'Pushed 2 commits to feat/menu-browsing-filters',
    description: 'Added dietary preference filter tags and cart total recalculation.',
    timestamp: '2026-08-27T16:45:00Z',
    user: CURRENT_USER,
    projectKey: 'TFD',
    badgeText: '2 commits',
  },
  {
    id: 'act-6',
    type: 'deployment',
    title: 'Deployed staging build v2.4.1',
    description: 'Autoscaler pod monitor successfully provisioned in us-east-1 cluster.',
    timestamp: '2026-08-26T20:30:00Z',
    user: TEAM_MEMBERS[3],
    projectKey: 'K8S',
    badgeText: 'Staging OK',
  },
];
